elevenlabs/packages

- packages/client/package.json
- packages/react/package.json
> chore: bump version 0.0.4

- packages/client/src/index.ts
- packages/client/src/utils/audioConcatProcessor.ts
- packages/client/src/utils/connection.ts
- packages/client/src/utils/events.ts
- packages/client/src/utils/input.ts
- packages/client/src/utils/output.ts
- packages/client/src/utils/rawAudioProcessor.ts
Adds support for the ulaw audio format based on the [wavefile library](https://github.com/rochars/wavefile/blob/master/lib/codecs/mulaw.js)
> Support ulaw format

- packages/client/package.json
- packages/client/src/utils/connection.ts
- packages/client/src/utils/events.ts
- packages/react/package.json
Adds `dynamic_variables` field to `conversation_initiation_client_data`.
> [convAI] add dynamic variables to conversation initialization event

- packages/client/package.json
- packages/react/package.json
Makes sure the react SDK behaves correctly when the server terminates the connection.
`onDisconnect` now receives a disconnection reason (`user`, `agent`, `error`) and a human-readable message in case of an error.
Our backend will soon start sending much clearer and more precise error messages.
> Improve disconnection handling

- packages/react/src/index.ts
> fix add get id to react

- packages/client/package.json
- packages/react/package.json
Bump to 0.1.0 to add support for `onAudio` callback
> Bump to 0.1.0

- packages/client/README.md
- packages/client/package.json
- packages/client/src/index.ts
- packages/client/src/utils/connection.ts
- packages/react/README.md
- packages/react/package.json
- packages/react/src/index.test.ts
- packages/react/src/index.ts
Also adds prettier to CI and adds missing `pt-br` language type
> Try to acquire a Wake Lock during conversation

- packages/client/README.md
- packages/client/package.json
- packages/client/src/index.ts
- packages/client/src/utils/events.ts
- packages/react/README.md
- packages/react/package.json
- packages/react/src/index.ts
Adds a method to `sendContextualUpdate` so some additional information can be passed onto agent without actually saying it. BE is implemented already.
> add support for contextual update events

- packages/client/README.md
- packages/client/package.json
- packages/client/src/index.ts
- packages/client/src/utils/events.ts
- packages/react/README.md
- packages/react/package.json
- packages/react/src/index.ts
Adds support for the upcoming message and activity events
> User messages

- examples/react-native-expo/.env.example
- examples/react-native-expo/.gitignore
- examples/react-native-expo/App.tsx
- examples/react-native-expo/README.md
Just some small nits based on how I usually work with expo.
> expo react native demo nits

- packages/client/package.json
- packages/client/src/index.test.ts
- packages/client/src/utils/WebRTCConnection.ts
- packages/client/src/version.ts
- packages/react/package.json
- packages/react/src/index.ts
- packages/react/src/version.ts
adds residency option and fixes onConnect
> add residency options to react

- packages/convai-cli/README.md
- packages/convai-cli/package.json
- packages/convai-cli/src/__tests__/config.test.ts
- packages/convai-cli/src/__tests__/residency.test.ts
- packages/convai-cli/src/__tests__/widget.test.ts
- packages/convai-cli/src/cli.ts
- packages/convai-cli/src/config.ts
- packages/convai-cli/src/elevenlabs-api.ts
adds residency option to config file of where to route requests and adds some tests
> [convai cli] add residency option

- packages/client/package.json
- packages/client/src/BaseConversation.ts
- packages/client/src/VoiceConversation.ts
- packages/client/src/utils/WebRTCConnection.ts
- packages/react/package.json
- packages/react/src/index.ts
Fixes https://github.com/elevenlabs/packages/issues/139
Fixes https://github.com/elevenlabs/packages/issues/106
Adds missing callbacks for WebRTC mode, like `onAudio` and `onCanSendFeedbackChange`.
> [WebRTC] Fix missing callbacks for WebRTC mode

- examples/react-native-expo/App.tsx
- packages/react-native/README.md
- packages/react-native/package.json
- packages/react-native/src/ElevenLabsProvider.tsx
- packages/react-native/src/hooks/useConversationSession.ts
- packages/react-native/src/utils/overrides.ts
Fixes https://github.com/elevenlabs/packages/issues/163
Fixes https://github.com/elevenlabs/packages/issues/174
Adds a new `conversation.setMicMuted` method and fixes `userId`.
> Add mic muted and fix userId

- packages/client/package.json
- packages/client/src/BaseConversation.ts
- packages/client/src/TextConversation.ts
- packages/client/src/VoiceConversation.ts
- packages/client/src/version.ts
- packages/react/package.json
- packages/react/src/version.ts
Fixes https://github.com/elevenlabs/packages/issues/172
Certain callbacks were incorrectly not set as optional.
> Make callbacks optional

- packages/client/package.json
- packages/client/src/BaseConversation.ts
- packages/client/src/VoiceConversation.ts
- packages/client/src/index.test.ts
- packages/client/src/utils/WebRTCConnection.ts
- packages/client/src/utils/WebSocketConnection.ts
- packages/client/src/version.ts
- packages/react/package.json
- packages/react/src/version.ts
Fixes https://github.com/elevenlabs/packages/issues/115
Attempts to fix https://github.com/elevenlabs/packages/issues/109 by adding more debug logic to determine what the problem is.
> Fix setVolume and add client tool debugging

- packages/client/README.md
- packages/client/src/BaseConversation.ts
- packages/client/src/VoiceConversation.ts
- packages/client/src/index.test.ts
- packages/client/src/index.ts
- packages/client/src/utils/BaseConnection.ts
- packages/client/src/utils/input.ts
- packages/client/src/utils/output.ts
- packages/react/README.md
- packages/react/src/index.ts
Creating a new PR as I don't have permissions to add to @jake-luster's [PR](https://github.com/elevenlabs/packages/pull/164)
> Add audio device controls

- packages/client/package.json
- packages/types/generated/types/asyncapi-types.ts
- packages/types/generated/types/incoming.ts
- packages/types/schemas/agent.asyncapi.yaml
- packages/types/scripts/generate-all-types.ts
- pnpm-lock.yaml
- Add new type package to elevenlabs/client
- Remove additionalProperties
- Add missing asyncapi types
> Complete AsyncAPI specification & fix type generation

- packages/convai-cli/package.json
- packages/convai-cli/src/__tests__/utils.test.ts
- packages/convai-cli/src/utils.ts
- packages/react/package.json
- packages/react/src/version.ts
> [cli] fix header conversion

- packages/agents-cli/README.md
- packages/agents-cli/src/__tests__/tools.test.ts
- packages/agents-cli/src/cli.ts
- packages/agents-cli/src/elevenlabs-api.ts
- packages/agents-cli/src/ui/views/FetchToolsView.tsx
adds command to fetch tools defined in xi into cli
> [agents cli] fetch tools

- packages/agents-cli/README.md
- packages/agents-cli/src/cli.ts
- packages/agents-cli/src/ui/views/HelpView.tsx
- Implements: `agents components add <component>`
> feat: add components cli for ui.elevenlabs.io
